/**
 * Copyright (c) 2014,2015 Enzien Audio, Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or
 * sublicense copies of the Software, strictly on a non-commercial basis,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * DO NOT MODIFY. THIS CODE IS MACHINE GENERATED BY THE SECTION6 HEAVY COMPILER.
 */

/*
 * System Includes
 */

#include <assert.h>
#include <math.h>
#include <string.h>
#include <stdarg.h>
#include "HvContext_heavy.h"
#include "HeavyMath.h"


/*
 * Function Declarations
 */

static void cBinop_botFQ_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_HWc2K_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_p1FiT_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_5QvxE_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_1bUsl_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_ThQ9q_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_otnq7_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_c8Us6_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_B0WQf_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_BoLat_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_rQ2Zu_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_UzBs7_sendMessage(HvBase *, int, const HvMessage *const);



/*
 * Static Helper Functions
 */

static void ctx_intern_scheduleMessageForReceiver(HvBase *const _c, const char *name, HvMessage *m) {
  switch (msg_symbolToHash(name)) {
    case 0xB762BB42: { // "Channel-B"
      ctx_scheduleMessage(_c, m, &cReceive_c8Us6_sendMessage, 0);
      break;
    }
    case 0xC440C54F: { // "Channel-A"
      ctx_scheduleMessage(_c, m, &cReceive_otnq7_sendMessage, 0);
      break;
    }
    default: return;
  }
}

static HvTable *ctx_intern_getTableForHash(HvBase *const _c, hv_uint32_t h) {
  switch (h) {

    default: return NULL;
  }
}



/*
 * Context Include and Implementatons
 */

Hv_heavy *hv_heavy_new(double sampleRate) {
  Hv_heavy *const _c = (Hv_heavy *) hv_malloc(sizeof(Hv_heavy));

  Base(_c)->numInputChannels = 0;
  Base(_c)->numOutputChannels = 2;
  Base(_c)->sampleRate = sampleRate;
  Base(_c)->blockStartTimestamp = 0;
  Base(_c)->f_scheduleMessageForReceiver = &ctx_intern_scheduleMessageForReceiver;
  Base(_c)->f_getTableForHash = &ctx_intern_getTableForHash;
  mq_initWithPoolSize(&Base(_c)->mq, 10); // 10KB MessagePool
  Base(_c)->basePath = NULL;
  Base(_c)->printHook = NULL;
  Base(_c)->sendHook = NULL;
  Base(_c)->userData = NULL;

  Base(_c)->numBytes = sizeof(Hv_heavy);
  Base(_c)->numBytes += sPhasor_k_init(&_c->sPhasor_GPLOH, 100.0f, sampleRate);
  Base(_c)->numBytes += sPhasor_k_init(&_c->sPhasor_8SvyU, 100.0f, sampleRate);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_HWc2K, 0.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_BoLat, 0.0f);

  // loadbang
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0.0), &cLoadbang_p1FiT_sendMessage, 0);
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0.0), &cLoadbang_rQ2Zu_sendMessage, 0);

  return _c;
}

void hv_heavy_free(Hv_heavy *_c) {


  hv_free(Base(_c)->basePath);
  mq_free(&Base(_c)->mq); // free queue after all objects have been freed, messages may be cancelled

  hv_free(_c);
}



/*
 * Static Function Implementation
 */

static void cBinop_botFQ_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sPhasor_k_onMessage(_c, &Context(_c)->sPhasor_GPLOH, 1, m);
}
static void cVar_HWc2K_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_ADD, 0.75f, 0, m, &cBinop_botFQ_sendMessage);
}
static void cLoadbang_p1FiT_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_HWc2K, 0, m, &cVar_HWc2K_sendMessage);
}
static void cBinop_5QvxE_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sPhasor_k_onMessage(_c, &Context(_c)->sPhasor_GPLOH, 0, m);
}
static void cBinop_1bUsl_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_ADD, 20.0f, 0, m, &cBinop_UzBs7_sendMessage);
}
static void cBinop_ThQ9q_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_ADD, 100.0f, 0, m, &cBinop_5QvxE_sendMessage);
}
static void cReceive_otnq7_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_MULTIPLY, 500.0f, 0, m, &cBinop_ThQ9q_sendMessage);
}
static void cReceive_c8Us6_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_MULTIPLY, 500.0f, 0, m, &cBinop_1bUsl_sendMessage);
}
static void cBinop_B0WQf_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sPhasor_k_onMessage(_c, &Context(_c)->sPhasor_8SvyU, 1, m);
}
static void cVar_BoLat_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_ADD, 0.75f, 0, m, &cBinop_B0WQf_sendMessage);
}
static void cLoadbang_rQ2Zu_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_BoLat, 0, m, &cVar_BoLat_sendMessage);
}
static void cBinop_UzBs7_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sPhasor_k_onMessage(_c, &Context(_c)->sPhasor_8SvyU, 0, m);
}



/*
 * Context Process Implementation
 */

#define HV_NUM_OUTPUT_CHANNELS 2

int hv_heavy_process(Hv_heavy *const _c, float **const inputBuffers, float **const outputBuffers, int n4) {
  n4 &= ~HV_N_SIMD_MASK; // ensure that the block size is a multiple of HV_N_SIMD
  const int n = n4;

#if HV_NUM_OUTPUT_CHANNELS > 0
  // declare temporary signal vars
  hv_bufferf_t Bf0, Bf1, Bf2, Bf3, Bf4;
  // no temporary integer buffers

  // declare the output vars
  hv_bufferf_t O0, O1;

  // declare and init the zero buffer
  hv_bufferf_t ZERO; sZero_process(VOf(ZERO));
#endif // HV_NUM_OUTPUT_CHANNELS > 0

  hv_uint32_t nextBlock = Base(_c)->blockStartTimestamp;
  while (n4) {

    // process all of the messages for this block
    nextBlock += HV_N_SIMD;
    while (mq_hasMessageBefore(&Base(_c)->mq, nextBlock)) {
      MessageNode *const node = mq_peek(&Base(_c)->mq);
      node->sendMessage(Base(_c), node->let, node->m);
      mq_pop(&Base(_c)->mq);
    }

#if HV_NUM_OUTPUT_CHANNELS > 0
    sZero_process(VOf(O0)); // clear the output vars
#if HV_NUM_OUTPUT_CHANNELS > 1
    sZero_process(VOf(O1));
#endif // HV_NUM_OUTPUT_CHANNELS > 1

    // process all signal functions
    __hv_phasor_k_f(&_c->sPhasor_GPLOH, VOf(Bf0));
    __hv_var_ks_f(VOf(Bf1), 0.5f, 0.0f, 0);
    __hv_sub_f(VIf(Bf0), VIf(Bf1), VOf(Bf1));
    __hv_abs_f(VIf(Bf1), VOf(Bf1));
    __hv_var_ks_f(VOf(Bf0), 0.25f, 0.0f, 0);
    __hv_sub_f(VIf(Bf1), VIf(Bf0), VOf(Bf0));
    __hv_var_ks_f(VOf(Bf1), 6.28319f, 0.0f, 0);
    __hv_mul_f(VIf(Bf0), VIf(Bf1), VOf(Bf1));
    __hv_mul_f(VIf(Bf1), VIf(Bf1), VOf(Bf0));
    __hv_mul_f(VIf(Bf1), VIf(Bf0), VOf(Bf2));
    __hv_var_ks_f(VOf(Bf3), 0.166667f, 0.0f, 0);
    __hv_mul_f(VIf(Bf2), VIf(Bf3), VOf(Bf3));
    __hv_sub_f(VIf(Bf1), VIf(Bf3), VOf(Bf3));
    __hv_mul_f(VIf(Bf2), VIf(Bf0), VOf(Bf0));
    __hv_var_ks_f(VOf(Bf2), 0.00833333f, 0.0f, 0);
    __hv_mul_f(VIf(Bf0), VIf(Bf2), VOf(Bf2));
    __hv_add_f(VIf(Bf3), VIf(Bf2), VOf(Bf2));
    __hv_phasor_k_f(&_c->sPhasor_8SvyU, VOf(Bf3));
    __hv_var_ks_f(VOf(Bf0), 0.5f, 0.0f, 0);
    __hv_sub_f(VIf(Bf3), VIf(Bf0), VOf(Bf0));
    __hv_abs_f(VIf(Bf0), VOf(Bf0));
    __hv_var_ks_f(VOf(Bf3), 0.25f, 0.0f, 0);
    __hv_sub_f(VIf(Bf0), VIf(Bf3), VOf(Bf3));
    __hv_var_ks_f(VOf(Bf0), 6.28319f, 0.0f, 0);
    __hv_mul_f(VIf(Bf3), VIf(Bf0), VOf(Bf0));
    __hv_mul_f(VIf(Bf0), VIf(Bf0), VOf(Bf3));
    __hv_mul_f(VIf(Bf0), VIf(Bf3), VOf(Bf1));
    __hv_var_ks_f(VOf(Bf4), 0.166667f, 0.0f, 0);
    __hv_mul_f(VIf(Bf1), VIf(Bf4), VOf(Bf4));
    __hv_sub_f(VIf(Bf0), VIf(Bf4), VOf(Bf4));
    __hv_mul_f(VIf(Bf1), VIf(Bf3), VOf(Bf3));
    __hv_var_ks_f(VOf(Bf1), 0.00833333f, 0.0f, 0);
    __hv_mul_f(VIf(Bf3), VIf(Bf1), VOf(Bf1));
    __hv_add_f(VIf(Bf4), VIf(Bf1), VOf(Bf1));
    __hv_add_f(VIf(Bf2), VIf(Bf1), VOf(Bf1));
    __hv_var_ks_f(VOf(Bf2), 0.5f, 0.0f, 0);
    __hv_mul_f(VIf(Bf1), VIf(Bf2), VOf(Bf2));
    __hv_add_f(VIf(Bf2), VIf(O0), VOf(O0));
    __hv_add_f(VIf(Bf2), VIf(O1), VOf(O1));
#endif // HV_NUM_OUTPUT_CHANNELS > 0

    // save output vars to output buffer (and update loop counters)
#if HV_NUM_OUTPUT_CHANNELS > 0
    sStore_process(outputBuffers[0], VIf(O0)); outputBuffers[0] += HV_N_SIMD;
#if HV_NUM_OUTPUT_CHANNELS > 1
    sStore_process(outputBuffers[1], VIf(O1)); outputBuffers[1] += HV_N_SIMD;
#endif // HV_NUM_OUTPUT_CHANNELS > 1
#endif // HV_NUM_OUTPUT_CHANNELS > 0
    n4 -= HV_N_SIMD;
  }

  Base(_c)->blockStartTimestamp = nextBlock;

  return n; // return the number of frames processed
}

int hv_heavy_process_inline(Hv_heavy *c, float *const inputBuffers, float *const outputBuffers, int n4) {
  int i = ctx_getNumInputChannels(Base(c));
  float **bIn = (float **) hv_alloca(i*sizeof(float *));
  while (i--) bIn[i] = inputBuffers+(i*n4);

  i = ctx_getNumOutputChannels(Base(c));
  float **bOut = (float **) hv_alloca(i*sizeof(float *));
  while (i--) bOut[i] = outputBuffers+(i*n4);

  int n = hv_heavy_process(c, bIn, bOut, n4);
  return n;
}
