/*
 * Copyright 2014 Section6. All Rights Reserved.
 *
 * DO NOT MODIFY. THIS CODE IS MACHINE GENERATED BY THE SECTION6 HEAVY COMPILER.
 */

#ifndef _HEAVYCONTEXT_HEAVY_H_
#define _HEAVYCONTEXT_HEAVY_H_

#include "HvBase.h"

#define Context(_x) ((Hv_heavy *) (_x))

// object includes
#include "SignalVar.h"
#include "HeavyMath.h"

typedef struct Hv_heavy {
  HvBase base;

  // objects
  SignalVarf sVarf_n0XoC;
} Hv_heavy;

#endif // _HEAVYCONTEXT_HEAVY_H_
