/*
 * Copyright 2014 Section6. All Rights Reserved.
 *
 * DO NOT MODIFY. THIS CODE IS MACHINE GENERATED BY THE SECTION6 HEAVY COMPILER.
 */

/*
 * System Includes
 */

#include <assert.h>
#include <math.h>
#include <string.h>
#include <stdarg.h>
#include "HvContext_heavy.h"
#include "HeavyMath.h"


/*
 * Function Declarations
 */





/*
 * Static Helper Functions
 */

static void ctx_intern_scheduleMessageForReceiver(HvBase *const _c, const char *name, HvMessage *m) {
  switch (msg_symbolToHash(name)) {

    default: return;
  }
}

static HvTable *ctx_intern_getTableForHash(HvBase *const _c, hv_uint32_t h) {
  switch (h) {

    default: return NULL;
  }
}



/*
 * Context Include and Implementatons
 */

Hv_heavy *hv_heavy_new(int numInputChannels, int numOutputChannels, double sampleRate) {
  Hv_heavy *const _c = (Hv_heavy *) hv_malloc(sizeof(Hv_heavy));

  Base(_c)->numInputChannels = numInputChannels;
  Base(_c)->numOutputChannels = numOutputChannels;
  Base(_c)->sampleRate = sampleRate;
  Base(_c)->blockStartTimestamp = 0;
  Base(_c)->f_scheduleMessageForReceiver = &ctx_intern_scheduleMessageForReceiver;
  Base(_c)->f_getTableForHash = &ctx_intern_getTableForHash;
  mq_initWithPoolSize(&Base(_c)->mq, 10); // 10KB MessagePool
  Base(_c)->basePath = NULL;
  Base(_c)->printHook = NULL;
  Base(_c)->sendHook = NULL;
  Base(_c)->userData = NULL;

  Base(_c)->numBytes = sizeof(Hv_heavy);
  Base(_c)->numBytes += sPhasor_k_init(&_c->sPhasor_LmKf7, 300.0f, sampleRate);

  // loadbang


  return _c;
}

void hv_heavy_free(Hv_heavy *_c) {


  hv_free(Base(_c)->basePath);
  mq_free(&Base(_c)->mq); // free queue after all objects have been freed, messages may be cancelled

  hv_free(_c);
}



/*
 * Static Function Implementation
 */





/*
 * Context Process Implementation
 */

#define HV_NUM_OUTPUT_CHANNELS 2

int hv_heavy_process(Hv_heavy *const _c, float **const inputBuffers, float **const outputBuffers, int n4) {
  n4 &= ~HV_N_SIMD_MASK; // ensure that the block size is a multiple of HV_N_SIMD
  const int n = n4;

#if HV_NUM_OUTPUT_CHANNELS > 0
  // declare temporary signal vars
  hv_bufferf_t Bf0;
  // no temporary integer buffers

  // declare the output vars
  hv_bufferf_t O0, O1;

  // declare and init the zero buffer
  hv_bufferf_t ZERO; sZero_process(VOf(ZERO));
#endif // HV_NUM_OUTPUT_CHANNELS > 0

  hv_uint32_t nextBlock = Base(_c)->blockStartTimestamp;
  while (n4) {

    // process all of the messages for this block
    nextBlock += HV_N_SIMD;
    while (mq_hasMessageBefore(&Base(_c)->mq, nextBlock)) {
      MessageNode *const node = mq_peek(&Base(_c)->mq);
      node->sendMessage(Base(_c), node->let, node->m);
      mq_pop(&Base(_c)->mq);
    }

#if HV_NUM_OUTPUT_CHANNELS > 0
    sZero_process(VOf(O0)); // clear the output vars
#if HV_NUM_OUTPUT_CHANNELS > 1
    sZero_process(VOf(O1));
#endif // HV_NUM_OUTPUT_CHANNELS > 1

    // process all signal functions
    __hv_phasor_k_f(&_c->sPhasor_LmKf7, VOf(Bf0));
    __hv_add_f(VIf(Bf0), VIf(O1), VOf(O1));
    __hv_add_f(VIf(Bf0), VIf(O0), VOf(O0));
#endif // HV_NUM_OUTPUT_CHANNELS > 0

    // save output vars to output buffer (and update loop counters)
#if HV_NUM_OUTPUT_CHANNELS > 0
    sStore_process(outputBuffers[0], VIf(O0)); outputBuffers[0] += HV_N_SIMD;
#if HV_NUM_OUTPUT_CHANNELS > 1
    sStore_process(outputBuffers[1], VIf(O1)); outputBuffers[1] += HV_N_SIMD;
#endif // HV_NUM_OUTPUT_CHANNELS > 1
#endif // HV_NUM_OUTPUT_CHANNELS > 0
    n4 -= HV_N_SIMD;
  }

  Base(_c)->blockStartTimestamp = nextBlock;

  return n; // return the number of frames processed
}

void hv_heavy_process_inline(Hv_heavy *c, float *const inputBuffers, float *const outputBuffers, int n4) {
  int i = ctx_getNumInputChannels(Base(c));
  float **bIn = (float **) hv_alloca(i*sizeof(float *));
  while (i--) bIn[i] = inputBuffers+(i*n4);

  i = ctx_getNumOutputChannels(Base(c));
  float **bOut = (float **) hv_alloca(i*sizeof(float *));
  while (i--) bOut[i] = outputBuffers+(i*n4);

  hv_heavy_process(c, bIn, bOut, n4);
}
