name: C/C++ CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '10-2020-q4'
    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v7
      with:
        version: 2.0.10
    - name: make
      run: make
    - name: make check
      run: make check
